### ISSUE TITLE
Math::IsPrime function error

### ISSUE THREAD

**Issue by TheMastermindInventor** [AnnoyingB/MathLib#2]
IsPrime function (Math.cpp) is implemented with some errors, I wrote a fresh algorithm for the function. Please test it and add it if you like :)
`bool IsPrime(int num1) {
    if(num1 == 0 || num1 == 1)
        return 0;
    
    else if(num1 == 2)
       return 1;
       
    int increment = 2;
    while(increment != num1){
        if(num1%increment == 0){
            return 0;
        }
        increment++;
    }
    return 1;
}`

**Comment by AnnoyingB** [comment]
I'll be sure to test it out, Thanks!

**Comment by AnnoyingB** [comment]
I have tested my code and it works fine, so does yours but I'll just use yours. Thanks.
